language: php
before_install:
  - pecl channel-update pecl.php.net
  - pecl install yaml < /dev/null
  - composer install
script:
  - composer run-script test
sudo: false
addons:
  apt:
    packages:
      - libyaml-dev
